"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var environment_1 = require("./environment");
var parser2_1 = require("./parser2");
var interpreter_1 = require("./interpreter");
var fs = require("fs");
var value_1 = require("./value");
var ntv_functions_1 = require("./ntv_functions");
var src = fs.readFileSync("./programII.txt", "utf-8");
var env = new environment_1.Environment();
env.declareVar("print", (0, value_1.MK_NTV_FUNCTION)(ntv_functions_1.print), true);
var parser = new parser2_1.default();
var ast = parser.produceAST(src);
var result = (0, interpreter_1.evaluate)(ast, env);
console.log(result);
